CREATE TABLE "users" (
  "id" bigserial PRIMARY KEY,
  "nik" varchar(16) UNIQUE NOT NULL,
  "full_name" varchar(100) NOT NULL,
  "legal_name" varchar(100) NOT NULL,
  "tempat_lahir" varchar(100) NOT NULL,
  "tanggal_lahir" date NOT NULL,
  "gaji" decimal(15,2) NOT NULL,
  "foto_ktp" varchar NOT NULL,
  "foto_selfie" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "loans" (
  "id" bigserial PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "loan_limit" decimal(15,2) NOT NULL,
  "term" int NOT NULL,
  "remaining_limit" decimal(15,2) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "loan_id" bigint NOT NULL,
  "nomor_kontrak" varchar(50) UNIQUE NOT NULL,
  "otr" decimal(15,2) NOT NULL,
  "admin_fee" decimal(15,2) NOT NULL,
  "jumlah_cicilan" decimal(15,2) NOT NULL,
  "jumlah_bunga" decimal(15,2) NOT NULL,
  "nama_asset" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX ON "users" ("nik");

CREATE INDEX ON "loans" ("user_id");

CREATE INDEX ON "transactions" ("user_id");

CREATE INDEX ON "transactions" ("loan_id");

CREATE INDEX ON "transactions" ("nomor_kontrak");

ALTER TABLE "loans" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("loan_id") REFERENCES "loans" ("id");
