// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Loan struct {
	ID             int64     `json:"id"`
	UserID         int64     `json:"user_id"`
	LoanLimit      string    `json:"loan_limit"`
	Term           int32     `json:"term"`
	RemainingLimit string    `json:"remaining_limit"`
	CreatedAt      time.Time `json:"created_at"`
}

type Transaction struct {
	ID            int32     `json:"id"`
	UserID        int64     `json:"user_id"`
	LoanID        int64     `json:"loan_id"`
	NomorKontrak  string    `json:"nomor_kontrak"`
	Otr           string    `json:"otr"`
	AdminFee      string    `json:"admin_fee"`
	JumlahCicilan string    `json:"jumlah_cicilan"`
	JumlahBunga   string    `json:"jumlah_bunga"`
	NamaAsset     string    `json:"nama_asset"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Nik          string    `json:"nik"`
	FullName     string    `json:"full_name"`
	LegalName    string    `json:"legal_name"`
	TempatLahir  string    `json:"tempat_lahir"`
	TanggalLahir time.Time `json:"tanggal_lahir"`
	Gaji         string    `json:"gaji"`
	FotoKtp      string    `json:"foto_ktp"`
	FotoSelfie   string    `json:"foto_selfie"`
	CreatedAt    time.Time `json:"created_at"`
}
